// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconCarbon:close': typeof import('~icons/carbon/close')['default']
    'IconCarbon:menu': typeof import('~icons/carbon/menu')['default']
    'IconCarbon:shoppingCart': typeof import('~icons/carbon/shopping-cart')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
